include: package:very_good_analysis/analysis_options.5.0.0.yaml
analyzer:
  errors:
    one_member_abstracts: ignore
    invalid_annotation_target: ignore
  exclude:
    - "**.g.dart"
    - "**.gr.dart"
    - "**.freezed.dart"
    - "**.config.dart"
    - "**.mocks.dart"
linter:
  rules:
    sort_pub_dependencies: false
    public_member_api_docs: false
    lines_longer_than_80_chars: false
    flutter_style_todos: false
