name: manga_clean_arch
description: A new Flutter project.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.0.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # State Management
  flutter_bloc: ^8.1.6

  # Caching
  hive_flutter: ^1.1.0
  hydrated_bloc: ^9.1.5

  # Networking
  dio: ^5.4.3+1
  dio_smart_retry: ^6.0.0
  pretty_dio_logger: ^1.3.1

  # Routing
  auto_route: ^8.2.0

  # Localization
  easy_localization: ^3.0.7

  # Depedency Injection
  get_it: ^7.7.0

  # Json Parsing
  json_annotation: ^4.9.0

  # Utility
  fpdart: ^1.1.0
  logger: ^2.3.0
  envied: ^0.5.4+1
  equatable: ^2.0.5
  path_provider: ^2.1.3
  stream_transform: ^2.1.0

  # UI
  lottie: ^3.1.2
  cupertino_icons: ^1.0.8
  flex_color_scheme: ^7.3.1
  cached_network_image: ^3.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Testing
  mocktail: ^1.0.4
  bloc_test: ^9.1.7

  # Code Generation
  build_runner: ^2.4.11
  hive_generator: ^2.0.1
  json_serializable: ^6.8.0
  envied_generator: ^0.5.4+1
  auto_route_generator: ^8.0.0

  # Linter
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true

  assets:
    - assets/translations/
    - assets/animations/
